# Generated by Django 5.0.7 on 2025-09-14 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieID', models.CharField(max_length=20, unique=True)),
                ('MovieTitle', models.CharField(max_length=200)),
                ('Actor1Name', models.CharField(max_length=120)),
                ('Actor2Name', models.CharField(blank=True, max_length=120)),
                ('DirectorName', models.CharField(max_length=120)),
                ('MovieGenre', models.CharField(choices=[('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Action', 'Action'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller'), ('Animation', 'Animation'), ('Other', 'Other')], max_length=20)),
                ('ReleaseYear', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2026)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
